import {Router} from 'express'; import {z} from 'zod'; import {db} from '../lib/db.js'; import crypto from 'node:crypto'; import {emailProvider} from '../lib/email.js'; import {hashPassword,verifyPassword,makeToken,setAuthCookie,clearAuthCookie,auth} from '../lib/auth.js';
const r=Router(); const credentials=z.object({email:z.string().email(),password:z.string().min(8),name:z.string().min(1).max(100).optional()});
r.post('/register',async(req,res)=>{const p=credentials.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid input',details:p.error.flatten()});const {email,password,name}=p.data;if(await db.user.findUnique({where:{email}}))return res.status(409).json({error:'Email already registered'});const user=await db.user.create({data:{email,passwordHash:await hashPassword(password),name,profile:{create:{}}}});setAuthCookie(res,makeToken(user.id));res.status(201).json({user:{id:user.id,email:user.email,name:user.name,role:user.role}})});
r.post('/login',async(req,res)=>{const p=credentials.pick({email:true,password:true}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid input'});const user=await db.user.findUnique({where:{email:p.data.email}});if(!user||!(await verifyPassword(p.data.password,user.passwordHash)))return res.status(401).json({error:'Invalid email or password'});setAuthCookie(res,makeToken(user.id));res.json({user:{id:user.id,email:user.email,name:user.name,role:user.role}})});
r.post('/verify/request',async(req,res)=>{const p=z.object({email:z.string().email()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid email'});const user=await db.user.findUnique({where:{email:p.data.email}});if(user){const token=crypto.randomBytes(32).toString('hex');await db.emailToken.create({data:{userId:user.id,type:'VERIFY',tokenHash:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:new Date(Date.now()+30*60*1000)}});await emailProvider.send(user.email,'Verify your Devsphere account',`Verify your account with token: ${token}`)}res.json({ok:true})});
r.post('/verify/confirm',async(req,res)=>{const token=String(req.body?.token||'');const hash=crypto.createHash('sha256').update(token).digest('hex');const row=await db.emailToken.findFirst({where:{tokenHash:hash,type:'VERIFY',usedAt:null,expiresAt:{gt:new Date()}}});if(!row)return res.status(400).json({error:'Invalid or expired token'});await db.$transaction([db.user.update({where:{id:row.userId},data:{verifiedAt:new Date()}}),db.emailToken.update({where:{id:row.id},data:{usedAt:new Date()}})]);res.json({ok:true})});
r.post('/password/request',async(req,res)=>{const p=z.object({email:z.string().email()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid email'});const user=await db.user.findUnique({where:{email:p.data.email}});if(user){const token=crypto.randomBytes(32).toString('hex');await db.emailToken.create({data:{userId:user.id,type:'RESET',tokenHash:crypto.createHash('sha256').update(token).digest('hex'),expiresAt:new Date(Date.now()+30*60*1000)}});await emailProvider.send(user.email,'Reset your Devsphere password',`Reset token: ${token}`)}res.json({ok:true})});
r.post('/password/confirm',async(req,res)=>{const p=z.object({token:z.string().min(20),password:z.string().min(8)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Invalid input'});const hash=crypto.createHash('sha256').update(p.data.token).digest('hex');const row=await db.emailToken.findFirst({where:{tokenHash:hash,type:'RESET',usedAt:null,expiresAt:{gt:new Date()}}});if(!row)return res.status(400).json({error:'Invalid or expired token'});await db.$transaction([db.user.update({where:{id:row.userId},data:{passwordHash:await hashPassword(p.data.password)}}),db.emailToken.update({where:{id:row.id},data:{usedAt:new Date()}})]);res.json({ok:true})});
r.post('/logout',auth,async(_req,res)=>{clearAuthCookie(res);res.status(204).end()}); r.get('/me',auth,(req,res)=>{const u=(req as any).user;res.json({user:{id:u.id,email:u.email,name:u.name,role:u.role}})}); export default r;
